services:
  qlever-backend:
    image: adfreiburg/qlever:commit-7bd9779 # freeze version.
    container_name: qlever-backend
    restart: unless-stopped
    ports:
      - "7001:7001"
    volumes:
      - ./Qlever_data:/index
    environment:
      - INDEX_PREFIX=olympics
    command: ServerMain -p 7001 -i /index/vldb-easy

  postgres:
    image: postgres:17
    container_name: postgres_instance
    restart: always
    environment:
      POSTGRES_USER: application_manager
      POSTGRES_PASSWORD: K33NUH5@?3z5
      POSTGRES_DB: tcc
    ports:
      - "5432:5432"
    volumes:
      - ./Postgres_data:/var/lib/postgresql/data
    shm_size: 128mb
  
  fuseki:
    image: stain/jena-fuseki:latest
    container_name: jena_fuseki_server
    restart: unless-stopped
    user: "${UID}:${GID}"
    ports:
      - "3131:3131"
    environment:
      - FUSEKI_HOME=/jena-fuseki
      - FUSEKI_BASE=/fuseki-base
      - JVM_ARGS=-Xmx2g
    volumes:
      - ./Fusekai_data:/fuseki-base
